sudo: required
services:
 - docker

before_install:
 - docker build -t hazelnut95/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true hazelnut95/docker-react npm run test

deploy:
 provider: elasticbeanstalk
 region: "ap-southeast-1"
#DockerReact-env.rnited8stf.ap-southeast-1.elasticbeanstalk.com
 app: "docker-react"
 env: "DockerReact-env"
 bucket_name: "elasticbeanstalk-ap-southeast-1-298344807027"
 bucket_path: "docker-react"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key:
  secure: $AWS_SECRET_KEY
